### ISSUE TITLE
Name of Existing Dataset: 311 City Service Requests in 2020

### ISSUE THREAD

**Issue by emkap01** [DCgov/opendatadc-requests#5]
Specify the dataset(s) in question with an Open Data DC URL: [311 City Service Requests in 2020](https://opendata.dc.gov/datasets/311-city-service-requests-in-2020/data?geometry=-77.216%2C38.934%2C-76.917%2C38.980&where=WARD%20%3D%20%274%27).

Would it be possible to have both an "Advisory Neighborhood Commission ID" as well as a "Single Member District ID" field added to the City Service Requests dataset (at least for the year 2020, if not also previous years?).  At present the only geographic boundary attributes available in the dataset are Zipcode and Ward.  Both fields are generally available in many of the other datasets hosted on opendata.dc.gov.

Adding the two new fields would make it possible to filter records by ANC and/or SMD, which could be very useful for analysis at a sub-Ward or multi-zipcode level.  

The absence of those fields can lead to flawed assumptions during analysis of 311 data.  By way of example, ANC 3/4G is split between Wards 3 and 4 - half of its Single Member Districts (3G07, 3G06 and 3G05) are all in Ward 3, while the other half (3G01, 3G02, 3G03 and 3G04) are all in Ward 4.

I tried to include an [ANC-level analysis of Christmas Tree pickup delays in a prototype civic engagement app I've been developing](https://cyvildc.com/story_slidedeck?story_id=913Q2SSL9Z1O&search_address=6200%20Oregon%20Ave%20NW%2C%20Washington%2C%20DC%2020015%2C%20USA&card_primary_key=), and queried opendata.dc.gov via API to grab all 311 records for Ward 3, not realizing that all of the records for half that ANC were excluded from the query, because they are (correctly) tagged as "Ward 4" in the data, even though they are within the boundaries of ANC 3G.

I was able to grab the missing records via separate API call and merge them into the dataset I used for the analysis, but only after I noticed the error when looking at the original results displayed on a map.

**Comment by asxantos** [comment]
Hi Erik, we pull the dataset from the Office of Unified Communications. Their 311 system uses the MAR address verification web service to obtain geographic boundaries like Ward. https://dcatlas.dcgis.dc.gov/mar/. I will forward your request to have the SMD and ANC added to the output of their geocoding, for their consideration. In the meantime you could work around this by,

The output for this includes a MARADDRESSREPOSITORYID. This ID relates to the District's official location identification datasets: [address points](https://opendata.dc.gov/datasets/address-points), [intersections](https://opendata.dc.gov/datasets/intersection-points), [block centroids](https://opendata.dc.gov/datasets/block-centroids) and [points of interest](https://opendata.dc.gov/datasets/points-of-interest). Related fields are ADDRESS_ID or MARID for intersections and block centroids. We have a page within opendata.dc.gov that gets into more detail for addressing: https://opendata.dc.gov/pages/addressing-in-dc.
