### ISSUE TITLE
Name of Existing Dataset: Crime Incidents in 2022

### ISSUE THREAD

**Issue by emkap01** [DCgov/opendatadc-requests#7]
Specify the dataset(s) in question with an Open Data DC URL: https://opendata.dc.gov/datasets/crime-incidents-in-2022/explore?location=38.904092%2C-77.012050%2C12.66

While bulk uploading recent crime records to my app, [cyvildc.com](https://cvildc.com), I noticed that some of the `LONGITUDE` values for some crime records appear to have been copied into the `LATITUDE` field.  Consequently, those records will not show up on any maps of the District.

By way of example, check out [the record for CCN 22008748](https://arcg.is/1ezHD40). You will notice that BOTH the `LATITUDE` and `LONGITUDE` values are identical, i.e., `-77.0795299633`.

There seems to be a bug somewhere upstream in the data pipeline.  I don't know how many records are impacted by it (some lat/lon values appear to be populated correctly in recent crime records), or when the bug was first introduced, but presumably it needs to be investigated and corrected.

If someone could please let me know once the data has been corrected, as well as when the error was first introduced, I would appreciate it. I'd like to purge the bad records from my database and then replace them with the corrected ones.

Thanks!

**Comment by asxantos** [comment]
Hello, we've corrected the data and you should be good to go. Thanks for catching this!
